# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, static ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1
      with:
        version: '1'
    
    - name: Setup the project environment
      run: julia --project -e 'using Pkg; Pkg.instantiate()'

    - name: run test
      run: julia --project -e 'using Pkg; Pkg.test("EDDP", coverage=true)'
    - name: Upload coverage
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        julia -e 'using Pkg;Pkg.add("Coverage")'
        julia -e 'using Coverage;Codecov.submit_local(process_folder())'
